// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByUserId(ctx context.Context, userID string) (User, error)
}

var _ Querier = (*Queries)(nil)
