// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, nickname, password, email, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Nickname,
		arg.Password,
		arg.Email,
	)
	return err
}

const getUserByUserId = `-- name: GetUserByUserId :one
SELECT id, user_id, nickname, password, email, created_at, updated_at, deleted_at FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByUserId(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserId, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Password,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
